intermidiate checkin

diff --git a/tests/system/suite/foglamp-test-template b/tests/system/suite/foglamp-test-template
--- a/tests/system/suite/foglamp-test-template
+++ b/tests/system/suite/foglamp-test-template
@@ -19,15 +19,67 @@ debug_mode=""
 test_to_run="0"
 print_help=false
 
-FOGLAMP_SUITE_BASEDIR=`realpath .`
-FOGLAMP_TEST_BASEDIR=`realpath ../test`
-FOGLAMP_BASEDIR=`realpath ../../..`
+# FOGLAMP_ROOT and FOGLAMP_DATA change these variables if you know the tests are going to need them
+# Alternatively, let the script find FogLAMP
+FACTORY_SETTING_ROOT="/usr/local/foglamp"
+FACTORY_SETTING_DATA="/usr/local/foglamp/data"
 
-MESSAGE="# This test file will be automatically generated by the test script."
+SUITE_SCRIPT=`basename ${0}`
+SUITE_NAME="`echo $SUITE_SCRIPT | sed 's/foglamp-test-//'`"
 
-echo "Suite DIR:   $FOGLAMP_SUITE_BASEDIR"
-echo "Test DIR:    $FOGLAMP_TEST_BASEDIR"
-echo "FogLAMP DIR: $FOGLAMP_BASEDIR"
+
+## Script Header
+print_header() {
+
+  echo "##### FogLAMP System Test #####"
+
+}
+
+
+## Script variables print
+print_vars() {
+
+  echo "Script Name:  $SUITE_NAME"
+  echo "Script Suite: $SUITE_SCRIPT"
+  echo "Suite DIR:    $SUITE_BASEDIR"
+  echo "Test DIR:     $TEST_BASEDIR"
+
+}
+
+
+## Set FogLAMP variables
+set_env_vars() {
+
+  # Check if a foglamp command exists - that usually means that a snap is installed
+  if ! [[ -x "$(command -v foglamp)" ]]; then
+
+    # Check FOGLAMP_ROOT and set it if it does not exist
+    if [ -z ${FOGLAMP_ROOT+x} ]; then
+      FOGLAMP_ROOT="$FACTORY_SETTING_ROOT"
+      export FOGLAMP_ROOT
+    fi
+
+    # Check if the FOGLAMP_ROOT directory exists
+    if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
+      echo "$SUITE_SCRIPT cannot be executed:"
+      echo "- foglamp is not a valid command"
+      echo "- ${FOGLAMP_ROOT} is not a valid directory."
+      exit 1
+    else
+      if [[ ! -x "${FOGLAMP_ROOT}/bin/foglamp" ]] && [[ ! -x "${FOGLAMP_ROOT}/scripts/foglamp" ]]; then
+        echo "$SUITE_SCRIPT cannot be executed: the foglamp script is not present in ${FOGLAMP_ROOT}."
+        exit 1
+      fi
+    fi
+  fi
+
+  # Set the suite dir
+  SUITE_BASEDIR=`realpath $SUITE_NAME`
+
+  # Set the test dir
+  TEST_BASEDIR=`realpath ../test`
+
+} 
 
 
 ##  Print the help screen
@@ -41,6 +93,12 @@ do_help() {
 	echo " -h | --help                Print this help"
 	echo " -d | --debug               The script is executed with set +x"
 	echo
+  echo "Environment Variables:"
+  echo " FOGLAMP_ROOT (default: /usr/local/foglamp)"
+  echo "            - The root directory for FogLAMP"
+  echo " FOGLAMP_DATA (default: /usr/local/foglamp/data"
+  echo "            - The data directory for FogLAMP"
+  echo ""
   echo "Tests:"
   echo
 	exit 0
@@ -154,6 +212,20 @@ do_all_tests () {
 }
 
 
+##################
+### MAIN LOGIC ###
+##################
+
+# Check if the suite name is valid
+if [[ $SUITE_SCRIPT != foglamp-test* ]]; then
+  echo "$SUITE_SCRIPT is not a valid suite name."
+  exit 1
+fi
+
+print_header
+set_env_vars
+print_vars
+
 ### Parameter Check ###
 while [ "$1" != "" ]; do
   case "$1" in
@@ -169,7 +241,7 @@ while [ "$1" != "" ]; do
       print_help=true
       ;;
     * )
-      echo "Usage: scaledb-test-performance --help"
+      echo "Usage: $SUITE_NAME --help"
       exit 1
       ;;
   esac
@@ -203,7 +275,7 @@ else
       do_006_truncate_table
       ;;
     * )
-      echo "Usage: scaledb-test-performance --help"
+      echo "Usage: $SUITE_NAME --help"
       exit 1
       ;;
   esac
