formatting fixes

diff --git a/scripts/core/selfssl b/scripts/core/selfssl
--- a/scripts/core/selfssl
+++ b/scripts/core/selfssl
@@ -32,30 +32,30 @@
 USAGE="Usage: ./`basename ${0}` CERTIFICATE_NAME EXPIRATION_DAYS"
 
 if [ "${FOGLAMP_ROOT}" = "" ]; then
-	FOGLAMP_ROOT=/usr/local/foglamp
+  FOGLAMP_ROOT=/usr/local/foglamp
 fi
 
 # include logger script
 . ${FOGLAMP_ROOT}/scripts/common/write_log.sh
 
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-    logger "Could not find the write_log script."
-    exit 1
+  logger "Could not find the write_log script."
+  exit 1
 fi
 
 # Logger wrapper
 selfssl_log() {
-    write_log "foglamp.script.core.selfssl" "$1" "$2" "$3"
+  write_log "foglamp.script.core.selfssl" "$1" "$2" "$3"
 }
 
 if [ -z $1 ]; then
-    selfssl_log "err" "${USAGE}" "logonly"
-    exit 1
+  selfssl_log "err" "${USAGE}" "logonly"
+  exit 1
 fi
 
 if [ -z $2 ]; then
-    selfssl_log "err" "${USAGE}" "logonly"
-    exit 1
+  selfssl_log "err" "${USAGE}" "logonly"
+  exit 1
 fi
 
 if ! [ -x "$(type -P openssl)" ]; then
@@ -67,20 +67,19 @@ fi
 # Check ENV VARS and decide the directory to place the certificates
 
 if [ ! -z ${FOGLAMP_DATA+x} ]; then
-    SSL_LOCATION="${FOGLAMP_DATA}"
+  SSL_LOCATION="${FOGLAMP_DATA}"
 else
-    if [ ! -z ${FOGLAMP_ROOT+x} ]; then
-        SSL_LOCATION="${FOGLAMP_ROOT}"
-    else
-        SSL_LOCATION="/usr/local/foglamp"
-    fi
+  if [ ! -z ${FOGLAMP_ROOT+x} ]; then
+    SSL_LOCATION="${FOGLAMP_ROOT}"
+  else
+    SSL_LOCATION="/usr/local/foglamp"
+  fi
 fi
 
 if [ ! -d "${SSL_LOCATION}" ]; then
-    selfssl_log "err" "Could not find the directory ${SSL_LOCATION} to put SSL certificates." "logonly"
-    exit 1
+  selfssl_log "err" "Could not find the directory ${SSL_LOCATION} to put SSL certificates." "logonly"
+  exit 1
 fi
-
 
 SSL_NAME=$1
 SSL_EXPIRATION_DAYS=$2
@@ -122,15 +121,15 @@ fi
 mv ${SSL_NAME}.key ${SSL_CERTS_PATH}/${SSL_NAME}.key > /dev/null
 mv_err=$?
 if [ ${mv_err} -ne 0 ]; then
-    selfssl_log "err" "Could not put SSL certificate ${SSL_NAME} at ${SSL_CERTS_PATH}" "logonly"
-    exit 1
+  selfssl_log "err" "Could not put SSL certificate ${SSL_NAME} key at ${SSL_CERTS_PATH}" "logonly"
+  exit 1
 fi
 
 mv ${SSL_NAME}.cert ${SSL_CERTS_PATH}/${SSL_NAME}.cert > /dev/null
 mv_err=$?
 if [ ${mv_err} -ne 0 ]; then
-    selfssl_log "err" "Could not put SSL certificate ${SSL_NAME} at ${SSL_CERTS_PATH}" "logonly"
-    exit 1
+  selfssl_log "err" "Could not put SSL certificate ${SSL_NAME} at ${SSL_CERTS_PATH}" "logonly"
+  exit 1
 fi
 
 # what about CSR
