FOGL-5477: version 1.2
Signed-off-by: Stefano <stefano@dianomic.com>

diff --git a/scripts/fledge_mnt b/scripts/fledge_mnt
--- a/scripts/fledge_mnt
+++ b/scripts/fledge_mnt
@@ -11,8 +11,66 @@
 ##
 ##--------------------------------------------------------------------
 
-set -e
+FLEDGE_MNT_VERSION=1.2
+
+#set -e
 #set -x
+
+#
+write_log() {
+
+  # Check log severity
+  case "$3" in
+    "debug")
+      severity="DEBUG"
+      ;;
+    "info")
+      severity="INFO"
+      ;;
+    "notice")
+      severity="WARNING"
+      ;;
+    "err")
+      severity="ERROR"
+      ;;
+    "crit")
+      severity="CRITICAL ERROR"
+      ;;
+    "alert")
+      severity="ALERT"
+      ;;
+    "emerg")
+      severity="EMERGENCY"
+      ;;
+    "*")
+      write_log $1 "err" "Internal error: unrecognized priority: $3" $4
+      exit 1
+      ;;
+  esac
+
+  # Log to syslog
+  if [[ "$5" =~ ^(logonly|all)$ ]]; then
+      tag="Fledge ${1}[${BASHPID}] ${severity}: ${2}"
+      fledge_log -t "${tag}" "${4}"
+  fi
+
+  # Log to Stdout
+  if [[ "${5}" =~ ^(outonly|all)$ ]]; then
+      if [[ "${6}" == "pretty" ]]; then
+          echo "${4}" >&2
+      else
+          echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $@" >&2
+      fi
+  fi
+
+}
+
+
+## fledge_log wrapper
+fledge_log() {
+    write_log "" "script.fledge_mnt" "$1" "$2" "$3" "$4"
+}
+
 
 #
 # FLEDGE_ROOT evaluation
@@ -22,7 +80,7 @@ if [ "${FLEDGE_ROOT}" = "" ]; then
 fi
 
 if [ ! -d "${FLEDGE_ROOT}" ]; then
-	logger "Fledge home directory missing or incorrectly set environment"
+	fledge_log "err" "Fledge home directory missing or incorrectly set environment :${FLEDGE_ROOT}:"  "outonly" "pretty"
 	exit 1
 fi
 
@@ -35,7 +93,7 @@ if [ ! -x "${FLEDGE_SCRIPT}" ]; then
     FLEDGE_SCRIPT="${FLEDGE_ROOT}/bin/fledge"
     if [ ! -x "${FLEDGE_SCRIPT}" ]; then
 
-	    logger "Fledge command unavailable both in deployment and development environments"
+	    fledge_log "err" "Fledge command unavailable both in deployment and development environments"  "outonly" "pretty"
 	    exit 1
     else
         FLEDGE_ENV="deployment"
@@ -49,7 +107,10 @@ fi
 #
 # sqlite3 command selection - identify the newer one for the availability of th recover command
 #
-SQLITE_SQL="${HOME}/bin/sqlite3"
+base_dir=$(dirname "$0")
+#echo "DBG ${base_dir}"
+#SQLITE_SQL="${HOME}/bin/sqlite3"
+SQLITE_SQL="${base_dir}/sqlite3"
 if ! [[ -x "${SQLITE_SQL}" ]]; then
 
     SQLITE_SQL="$FLEDGE_ROOT/plugins/storage/sqlite/sqlite3"
@@ -57,8 +118,8 @@ if ! [[ -x "${SQLITE_SQL}" ]]; then
 
         # Check system default SQLite 3 command line is available
         if ! [[ -x "$(command -v sqlite3)" ]]; then
-            sqlite_log "info" "The sqlite3 command cannot be found. Is SQLite3 installed?" "outonly" "pretty"
-            sqlite_log "info" "If SQLite3 is installed, check if the bin dir is in the PATH." "outonly" "pretty"
+            fledge_log "info" "The sqlite3 command cannot be found. Is SQLite3 installed?" "outonly" "pretty"
+            fledge_log "info" "If SQLite3 is installed, check if the bin dir is in the PATH." "outonly" "pretty"
             exit 1
         else
             SQLITE_SQL="$(command -v sqlite3)"
@@ -66,10 +127,16 @@ if ! [[ -x "${SQLITE_SQL}" ]]; then
     fi
 fi
 
+export SQLITE_SQL_ANALYZER="${base_dir}/sqlite3_analyzer"
+if ! [[ -x "${SQLITE_SQL_ANALYZER}" ]]; then
+
+    fledge_log "info" "sqlite3_analyzer not available in :${SQLITE_SQL_ANALYZER}:" "outonly" "pretty"
+    SQLITE_SQL_ANALYZER=""
+fi
+
 #
 # Configurations
 #
-FLEDGE_MNT_VERSION=1.0
 FLEDGE_DB="${FLEDGE_ROOT}/data/fledge.db"
 
 #
@@ -80,9 +147,8 @@ fledge_stop() {
     seconds=5
     ${FLEDGE_SCRIPT} stop
 
-    #  // FIXME_I:
-    #echo "sleeping ${seconds} seconds before fledge kill, to ensure everything is not running"
-    #sleep ${seconds}
+    echo "sleeping ${seconds} seconds before fledge kill, to ensure everything is not running"
+    sleep ${seconds}
     ${FLEDGE_SCRIPT} kill
 }
 
@@ -96,33 +162,35 @@ operation_start() {
 
 }
 
-fledge_check() {
-
-    operation_start "Executing database check"
-    fledge_stop
-
-    echo -n "Checking database consistency : "
-    time "${SQLITE_SQL}" "${FLEDGE_DB}" "pragma integrity_check;"
-}
-
 
 
 fledge_info_table() {
     fledge_table=$1
-    count=$2
+    option=$2
+    execute_count=no
 
     echo "Information on the table : ${fledge_table}"
 
-    echo -en "\tMIN Id : "
-    "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT min(id) FROM ${fledge_table} "
+    if [[ "${option}" == "count" ]]; then
 
-    echo -en "\tMAX Id : "
-    "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT max(id) FROM ${fledge_table} "
+        execute_count=yes
+    fi
 
-    if [[ "${count}" == "count" ]]; then
+    if [[ "${option}" == "count_only" ]]; then
+
+        execute_count=yes
+    else
+        echo -en "\tMIN Id : "
+        "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT min(id) FROM ${fledge_table} "
+
+        echo -en "\tMAX Id : "
+        "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT max(id) FROM ${fledge_table} "
+    fi
+
+    if [[ "${execute_count}" == "yes" ]]; then
 
         echo -en "\tCOUNT  : "
-        "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT count(id) FROM ${fledge_table} "
+        "${SQLITE_SQL}" "${FLEDGE_DB}" "SELECT count(*) FROM ${fledge_table} "
     fi
 
     echo ""
@@ -139,8 +207,40 @@ fledge_info() {
     fledge_info_table "STATISTICS_HISTORY"
     fledge_info_table "TASKS"              "count"
     fledge_info_table "LOG"                "count"
-
+    fledge_info_table "PLUGIN_DATA"        "count_only"
+    fledge_info_table "STREAMS"            "count_only"
 }
+
+fledge_analyze() {
+
+    if [[ "${SQLITE_SQL_ANALYZER}" == "" ]]; then
+
+        fledge_log "info" "sqlite3_analyzer not available in :${SQLITE_SQL_ANALYZER}:" "outonly" "pretty"
+        exit 1
+    else
+        export_analyze="${FLEDGE_DB}_analyze"
+
+        operation_start "Executing sqlite3_analyzer, output :${export_analyze}: "
+
+        "${SQLITE_SQL_ANALYZER}" "${FLEDGE_DB}"   > "${export_analyze}"
+    fi
+}
+
+fledge_check() {
+
+    operation_start "Executing database check"
+    fledge_stop
+    time_start=$(date +%s)
+
+
+    echo -n "Checking database consistency : "
+    "${SQLITE_SQL}" "${FLEDGE_DB}" "pragma integrity_check;"
+
+    time_end=$(date +%s)
+    echo "Operation completed : $(date)"
+    echo "Elapsed :$(($time_end - $time_start)): seconds"
+}
+
 
 #
 # Comment code for debug
@@ -373,8 +473,11 @@ fledge_help() {
     echo ""
     echo "${USAGE}
 The script is used to check/recovery fledge
+
 Arguments:
+
  info              - show information on the database/tables
+ analyze           - generate a text file with information about the database
  check             - check the fledge database, stops Fledge
  shrink            - shrink the database, stops Fledge
  shrink  --table   - delete the content of the statistics_history > 3 days and shrink the database
@@ -397,9 +500,9 @@ echo "Environment     : ${FLEDGE_ENV}"
 echo "Database        : ${FLEDGE_DB}"
 echo "sqlite3 command : ${SQLITE_SQL}"
 echo "sqlite3 version : $(${SQLITE_SQL} --version)"
+echo "sqlite3_analyzer: ${SQLITE_SQL_ANALYZER}"
 
-
-USAGE="Usage: `basename ${0}` {info|check|shrink --table|recover --custom}"
+USAGE="Usage: `basename ${0}` {info|analyze|check|shrink --table|recover --custom}"
 
 RECOVER_MODE=''
 SHRINK_MODE=''
@@ -408,6 +511,9 @@ SHRINK_MODE=''
 case "$1" in
     info)
         fledge_info
+        ;;
+    analyze)
+        fledge_analyze
         ;;
     check)
         fledge_check
