scripts reorganised

diff --git a/scripts/foglamp b/scripts/foglamp
--- a/scripts/foglamp
+++ b/scripts/foglamp
@@ -32,25 +32,6 @@ if [ -z ${FOGLAMP_ROOT+x} ]; then
     export FOGLAMP_ROOT
 fi
 
-# Set FOGLAMP_DATA if it does not exist
-if [ -z ${FOGLAMP_DATA+x} ]; then
-    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
-    export FOGLAMP_DATA
-fi
-
-# Check if $FOGLAMP_DATA exists
-if [[ -e ${FOGLAMP_DATA} ]]; then
-
-    # Check if $FOGLAMP_DATA is a directory
-    if [[ ! -d ${FOGLAMP_DATA} ]]; then
-        write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
-        exit 1
-    fi
-else
-    # $FOGLAMP_DATA does not exist: create it
-    mkdir -p ${FOGLAMP_DATA}
-fi
-
 # Check if the default directory exists
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
     write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
@@ -58,6 +39,28 @@ if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
     write_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
     write_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
     exit 1
+fi
+
+# Set FOGLAMP_DATA if it does not exist
+if [ -z ${FOGLAMP_DATA+x} ]; then
+    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
+    export FOGLAMP_DATA
+fi
+
+# Check if $FOGLAMP_DATA exists and is a directory
+if [[ ! -d ${FOGLAMP_DATA} ]]; then
+    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
+    exit 1
+fi
+
+# Check if the configuration file exists
+if [[ ! -e "$FOGLAMP_DATA/etc/foglamp.json" ]]; then
+
+    # Missing configuration file
+    write_log "err" "FogLAMP cannot start." "all" "pretty"
+    write_log "err" "FogLAMP configuration file foglamp.json not found." "all" "pretty"
+    exit 1
+
 fi
 
 
diff --git a/scripts/plugins/storage/postgres b/scripts/plugins/storage/postgres
--- a/scripts/plugins/storage/postgres
+++ b/scripts/plugins/storage/postgres
@@ -19,7 +19,7 @@
 set -e
 #set -x
 
-USAGE="Usage: `basename ${0}` {start|stop|status|init|reset|help} {managed|unmanaged}"
+USAGE="Usage: `basename ${0}` {start|stop|status|init|reset|help}"
 
 # Check FOGLAMP_ROOT
 if [ -z ${FOGLAMP_ROOT+x} ]; then
@@ -29,75 +29,24 @@ fi
 
 # Check if the default directory exists
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
-    write_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
-    write_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
-    write_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
+
+    # Here we cannot use the logger because we cannot find the write_log script.
+    # But it is ok, because the script is called with source and if it is called
+    # as standalone script the echo will be captured.
+    echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
+    echo "Specify the base directory for FogLAMP and set the variable with:"
+    echo "export FOGLAMP_ROOT=<basedir>"
     exit 1
-fi
 
-# Set FOGLAMP_DATA if it does not exist
-if [ -z ${FOGLAMP_DATA+x} ]; then
-    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
-fi
-
-# Check if $FOGLAMP_DATA exists
-if [[ -e ${FOGLAMP_DATA} ]]; then
-
-    # Check if $FOGLAMP_DATA is a directory
-    if [[ ! -d ${FOGLAMP_DATA} ]]; then
-        write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
-        exit 1
-    fi
-else
-    # $FOGLAMP_DATA does not exist: create it
-    mkdir -p ${FOGLAMP_DATA}
 fi
 
 
-## The Logging Handler
-#
-# Paramaters: $1 - Severity:
-#                  - debug
-#                  - info
-#                  - notice
-#                  - err
-#                  - crit
-#                  - alert
-#                  - emerg
-#             $2 - Message
-#             $3 - Output:
-#                  - logonly : send the message only to syslog
-#                  - all     : send the message to syslog and stdout
-#                  - outonly " send the message only to stdout
-#             $4 - Format
-#                - pretty : Do not show the date and priority
-#
-write_log() {
-
-    MODULE="foglamp.storage.postgres"
-
-    # Check log severity
-    if ! [[ "$1" =~ ^(debug|info|notice|err|crit|alert|emerg)$ ]]; then
-        write_log "err" "Internal error: unrecognized priority: $1" $3
-        exit 1
-    fi
-
-    # Log to syslog
-    if [[ "$3" =~ ^(logonly|all)$ ]]; then
-        logger -p local0.$1 -t $MODULE $2
-    fi
-
-    # Log to Stdout
-    if [[ "$3" =~ ^(outonly|all)$ ]]; then
-        if [[ "$4" == "pretty" ]]; then
-            echo "$2" >&2
-        else
-            echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $@" >&2
-        fi
-    fi
-
-}
+##########
+## INCLUDE SECTION
+##########
+. $FOGLAMP_ROOT/scripts/common/get_engine_management
+. $FOGLAMP_ROOT/scripts/common/write_log
 
 
 ## PostgreSQL Start
@@ -373,11 +322,32 @@ Arguments:
 }
 
 
+##################
 ### Main Logic ###
+##################
 
+# Set FOGLAMP_DATA if it does not exist
+if [ -z ${FOGLAMP_DATA+x} ]; then
+    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
+fi
+
+# Check if $FOGLAMP_DATA exists
+if [[ ! -d ${FOGLAMP_DATA} ]]; then
+    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
+    exit 1
+fi
+
+# Check if the Configuration file exists
+if [[ ! -e ${FOGLAMP_DATA}/etc/foglamp.json ]]; then
+    write_log "err" "Missing FogLAMP configuration file ${FOGLAMP_DATA}/etc/foglamp.json" "all" "pretty"
+    exit 1
+fi
+
+# Extract plugin
+engine_management=`get_engine_management $PLUGIN`
 # Settings if the database is managed by FogLAMP
-case "$2" in
-    "managed")
+case "$engine_management" in
+    "true")
 
         MANAGED=true
 
@@ -409,7 +379,7 @@ case "$2" in
         print_output="noisy"
         ;;
     
-    *)
+    "false")
 
         # This case includes UNMANAGED
 
@@ -425,6 +395,14 @@ case "$2" in
         # messages when we start or stop the server
         print_output="silent"
         MANAGED=false
+        ;;
+
+    *)
+
+        # Unexpected value from the configuation file
+        write_log "err" "FogLAMP cannot start." "all" "pretty"
+        write_log "err" "Missing plugin information in FogLAMP configuation file foglamp.json" "all" "pretty"
+        exit 1
         ;;
 
 esac
diff --git a/scripts/storage b/scripts/storage
--- a/scripts/storage
+++ b/scripts/storage
@@ -22,9 +22,74 @@
 # is embedded in FogLAMP
 #
 
-set -e
+#set -x
 
-source "$FOGLAMP_ROOT/scripts/plugins/storage/postgres" $1 unmanaged
+
+PLUGIN_TO_USE=""
+
+get_default_storage_plugin() {
+
+    # Remove new lines and store in a variable
+    json_foglamp=`tr -d '\n' < $1`
+
+    # Remove tabs
+    json_foglamp=`echo $json_foglamp | tr -d '\t'`
+
+    echo `echo $json_foglamp | grep -o '"default storage plugin" *:.*' | grep -o ':.*' | grep -o '".*' | cut -d'"' -f2`
+}
+
+get_plugin_from_storage() {
+
+    # Remove new lines and store in a variable
+    json_storage=`tr -d '\n' < $1`
+
+    # Remove tabs
+    json_storage=`echo $json_storage | tr -d '\t'`
+
+    echo `echo $json_storage | grep -o '"plugin" *: *{.*' | grep -o '{.*' | grep -o '"value" *:.*' | grep -o ':.*' | grep -o '".*' | cut -d'"' -f2`
+}
+
+
+#############
+## MAIN LOGIC
+#############
+
+# Check if the storage cache file exists
+if [[ -e "$FOGLAMP_DATA/etc/storage.json" ]]; then
+
+    # Extract plugin
+    PLUGIN_TO_USE=`get_plugin_from_storage "$FOGLAMP_DATA/etc/storage.json"`
+
+    # Check if the plugin has been found
+    if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then
+        write_log "err" "Missing plugin in FogLAMP storage cache file storage.json" "all" "pretty"
+    fi
+
+fi
+
+if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then
+
+    # Extract the default storage plugin from the configuration file
+    PLUGIN_TO_USE=`get_default_storage_plugin "$FOGLAMP_DATA/etc/foglamp.json"`
+    if [[ "${#PLUGIN_TO_USE}" -eq 0 ]]; then
+        write_log "err" "FogLAMP cannot start." "all" "pretty"
+        write_log "err" "Missing default plugin in FogLAMP configuration file foglamp.json" "all" "pretty"
+        exit 1
+    fi
+
+fi
+
+PLUGIN_SCRIPT="$FOGLAMP_ROOT/scripts/plugins/storage/$PLUGIN_TO_USE"
+if [[ ! -x "$PLUGIN_SCRIPT" ]]; then
+
+    # Missing storage plugin script
+    write_log "err" "FogLAMP cannot start." "all" "pretty"
+    write_log "err" "Missing Storage Plugin script $PLUGIN_SCRIPT." "all" "pretty"
+    exit 1
+
+fi
+
+source "$PLUGIN_SCRIPT" $1
 
 # exit cannot be used because the script is sourced.
 #exit $?
