FOGL-1310 - Add authentication for foglamp_status if ping requires authentication Warning: Because foglamp_status is used by foglamp_stop and foglamp_start, if interactive password prompting is used then the user will be prompted multiple times for the password. Use of sub-sheels makes this difficult to avoid without persisting response in a file, which woudl be a security breach.

diff --git a/scripts/foglamp b/scripts/foglamp
--- a/scripts/foglamp
+++ b/scripts/foglamp
@@ -167,12 +167,16 @@ foglamp_start() {
                     foglamp_log "err" "Check ${FOGLAMP_DATA}/core.err for more information." "outonly" "pretty"
                     exit 1
                     ;;
+
+                  *)
+                    echo "Result X${new_attempt}X"
+                    ;;
                 esac
             done
             ;;
 
         *)
-            foglamp_log "err" "Unknown return status." "all"
+            foglamp_log "err" "Unknown return status, $result." "all"
             exit 1
             ;;
     esac
@@ -194,7 +198,6 @@ foglamp_stop() {
 
   if [[ "${result}" =~ "Forbidden" ]]; then
     token=`foglamp_authenticate`
-    echo " "
     if [[ "${token}" =~ "failed" ]]; then
         foglamp_log "info" "Failed authentication when attempting to stop foglamp." "all" "pretty"
         echo "Authentication failed."
@@ -328,6 +331,16 @@ foglamp_status() {
     # Get/Updates the rest API URL
     get_rest_api_url
     result=`curl -k -s ${REST_API_URL}/foglamp/ping || true`
+
+    if [[ "${result}" =~ "Forbidden" ]]; then
+      token=`foglamp_authenticate`
+      if [[ "${token}" =~ "failed" ]]; then
+          foglamp_log "info" "Failed authentication when attempting to get foglamp status." "all" "pretty"
+          echo "Authentication failed."
+          exit 0
+      fi
+      result=`curl -H "authorization: $token" -k -s ${REST_API_URL}/foglamp/ping || true`
+    fi
 
     case "$result" in
 
