changed the FOGLAMP_DATA destination

diff --git a/scripts/foglamp b/scripts/foglamp
--- a/scripts/foglamp
+++ b/scripts/foglamp
@@ -32,12 +32,31 @@ if [ -z ${FOGLAMP_ROOT+x} ]; then
     export FOGLAMP_ROOT
 fi
 
+# Set FOGLAMP_DATA if it does not exist
+if [ -z ${FOGLAMP_DATA+x} ]; then
+    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
+    export FOGLAMP_DATA
+fi
+
+# Check if $FOGLAMP_DATA exists
+if [[ -e ${FOGLAMP_DATA} ]]; then
+
+    # Check if $FOGLAMP_DATA is a directory
+    if [[ ! -d ${FOGLAMP_DATA} ]]; then
+        write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
+        exit 1
+    fi
+else
+    # $FOGLAMP_DATA does not exist: create it
+    mkdir -p ${FOGLAMP_DATA}
+fi
+
 # Check if the default directory exists
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-    foglamp_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
-    foglamp_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
-    foglamp_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
-    foglamp_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
+    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
+    write_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
+    write_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
+    write_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
     exit 1
 fi
 
@@ -60,13 +79,13 @@ fi
 #             $4 - Format
 #                - pretty : Do not show the date and priority
 #
-foglamp_log() {
+write_log() {
 
     MODULE="foglamp.core"
 
     # Check log severity
     if ! [[ "$1" =~ ^(debug|info|notice|err|crit|alert|emerg)$ ]]; then
-        foglamp_log "err" "Internal error: unrecognized priority: $1" $3
+        write_log "err" "Internal error: unrecognized priority: $1" $3
         exit 1
     fi
 
@@ -92,14 +111,14 @@ foglamp_start() {
 
     # Check the storage management script
     if [[ ! -e "$FOGLAMP_ROOT/scripts/storage/storage_data" ]]; then
-        foglamp_log "info" "FogLAMP cannot start." "all" "pretty"
-        foglamp_log "err" "FogLAMP Storage Plugin not found." "all" "pretty"
+        write_log "info" "FogLAMP cannot start." "all" "pretty"
+        write_log "err" "FogLAMP Storage Plugin not found." "all" "pretty"
         exit 1
     fi
 
     # Check the Python environment
     if ! [[ -x "$(command -v python3)" ]]; then
-        foglamp_log "err" "Python interpreter not found, FogLAMP cannot start." "all" "pretty"
+        write_log "err" "Python interpreter not found, FogLAMP cannot start." "all" "pretty"
         exit 1
     fi
 
@@ -112,8 +131,8 @@ foglamp_start() {
     # Start the Storage Plugin for the Data
     source "$FOGLAMP_ROOT/scripts/storage/storage_data" start
     if [ $? -ne 0 ];then
-        foglamp_log "info" "FogLAMP cannot start" "all" "pretty"
-        foglamp_log "err" "FogLAMP database is not ready." "all" "pretty"
+        write_log "info" "FogLAMP cannot start" "all" "pretty"
+        write_log "err" "FogLAMP database is not ready." "all" "pretty"
         exit 1
     fi
 
@@ -122,7 +141,7 @@ foglamp_start() {
 
         "0")
             #FogLAMP already running
-            foglamp_log "info" "FogLAMP is already running." "all" "pretty"
+            write_log "info" "FogLAMP is already running." "all" "pretty"
             ;;
 
         "2")
@@ -131,15 +150,15 @@ foglamp_start() {
             export PYTHONPATH
             if [[ -e "$PYTHONPATH/foglamp/services/core/__main__.py" ]]; then
                 python3 -m foglamp.services.core > /dev/null 2>&1 & disown
-                foglamp_log "info" "FogLAMP started." "all" "pretty"
+                write_log "info" "FogLAMP started." "all" "pretty"
             else
-                foglamp_log "err" "FogLAMP core not found." "all" "pretty"
+                write_log "err" "FogLAMP core not found." "all" "pretty"
                 exit 1
             fi
             ;;
 
         *)
-            foglamp_log "err" "Unknown return status." "all"
+            write_log "err" "Unknown return status." "all"
             exit 1
             ;;
     esac
@@ -155,8 +174,8 @@ foglamp_stop() {
 
     # Check the storage management script
     if [[ ! -e "$FOGLAMP_ROOT/scripts/storage/storage_data" ]]; then
-        foglamp_log "info" "FogLAMP cannot be stopped." "all" "pretty"
-        foglamp_log "err" "FogLAMP Storage Plugin not found." "all" "pretty"
+        write_log "info" "FogLAMP cannot be stopped." "all" "pretty"
+        write_log "err" "FogLAMP Storage Plugin not found." "all" "pretty"
         exit 1
     fi
 
@@ -178,7 +197,7 @@ foglamp_stop() {
     # Stop the Storage Plugin for the Data
     source "$FOGLAMP_ROOT/scripts/storage/storage_data" stop
     
-    foglamp_log "info" "FogLAMP stopped." "all" "pretty"
+    write_log "info" "FogLAMP stopped." "all" "pretty"
 
 }
 
@@ -189,8 +208,8 @@ foglamp_status() {
 
     # Check if curl is present
     if [[ ! `command -v curl` ]]; then
-        foglamp_log "info" "FogLAMP cannot be checked." "outonly" "pretty"
-        foglamp_log "info" "The curl command cannot be executed." "outonly" "pretty"
+        write_log "info" "FogLAMP cannot be checked." "outonly" "pretty"
+        write_log "info" "The curl command cannot be executed." "outonly" "pretty"
     fi
 
     result=`curl -s http://localhost:8081/foglamp/ping || true`
@@ -201,12 +220,12 @@ foglamp_status() {
                 echo "0"
             else
                 tot_sec=`echo $result | cut -d":" -f2 | cut -d"." -f1`
-                foglamp_log "info" "FogLAMP running." "outonly" "pretty"
-                foglamp_log "info" "FogLAMP uptime: $tot_sec seconds." "outonly" "pretty"
+                write_log "info" "FogLAMP running." "outonly" "pretty"
+                write_log "info" "FogLAMP uptime: $tot_sec seconds." "outonly" "pretty"
 
                 # Show Services
-                foglamp_log "info" "=== FogLAMP services:" "outonly" "pretty"
-                foglamp_log "info" "foglamp.services.core" "outonly" "pretty"
+                write_log "info" "=== FogLAMP services:" "outonly" "pretty"
+                write_log "info" "foglamp.services.core" "outonly" "pretty"
                 ps -ef | grep "$FOGLAMP_ROOT//services/storage" | grep -v 'grep' | awk '{print "foglamp.services.storage " $9 " " $10}' || true
                 ps -ef | grep "$FOGLAMP_ROOT//services/south" | grep -v 'grep' | awk '{print "foglamp.services.south " $9 " " $10}' || true
                 ps -ef | grep "$FOGLAMP_ROOT//services/north" | grep -v 'grep' | awk '{print "foglamp.services.north " $9 " " $10}' || true
@@ -214,7 +233,7 @@ foglamp_status() {
                 ps -ef | grep -o 'python3 -m foglamp.services.north.*' | grep -o 'foglamp.services.north.*' | grep -v 'foglamp.services.north\.\*' || true
 
                 # Show Tasks
-                foglamp_log "info" "=== FogLAMP tasks:" "outonly" "pretty"
+                write_log "info" "=== FogLAMP tasks:" "outonly" "pretty"
                 ps -ef | grep -o 'python3 -m foglamp.tasks.*' | grep -o 'foglamp.tasks.*' | grep -v 'foglamp.tasks\.\*' || true
             fi
             ;;
@@ -223,13 +242,13 @@ foglamp_status() {
                 if [[ "$1" == "silent" ]]; then
                     echo "0"
                 else
-                    foglamp_log "info" "FogLAMP starting." "outonly" "pretty"
+                    write_log "info" "FogLAMP starting." "outonly" "pretty"
                 fi
             else
                 if [[ "$1" == "silent" ]]; then
                     echo "2"
                 else
-                    foglamp_log "info" "FogLAMP not running." "outonly" "pretty"
+                    write_log "info" "FogLAMP not running." "outonly" "pretty"
                 fi
             fi
             ;;
diff --git a/scripts/plugins/storage/postgres b/scripts/plugins/storage/postgres
--- a/scripts/plugins/storage/postgres
+++ b/scripts/plugins/storage/postgres
@@ -29,11 +29,29 @@ fi
 
 # Check if the default directory exists
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-    foglamp_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
-    foglamp_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
-    foglamp_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
-    foglamp_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
+    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
+    write_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
+    write_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
+    write_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
     exit 1
+fi
+
+# Set FOGLAMP_DATA if it does not exist
+if [ -z ${FOGLAMP_DATA+x} ]; then
+    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
+fi
+
+# Check if $FOGLAMP_DATA exists
+if [[ -e ${FOGLAMP_DATA} ]]; then
+
+    # Check if $FOGLAMP_DATA is a directory
+    if [[ ! -d ${FOGLAMP_DATA} ]]; then
+        write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
+        exit 1
+    fi
+else
+    # $FOGLAMP_DATA does not exist: create it
+    mkdir -p ${FOGLAMP_DATA}
 fi
 
 
@@ -55,13 +73,13 @@ fi
 #             $4 - Format
 #                - pretty : Do not show the date and priority
 #
-pg_log() {
+write_log() {
 
     MODULE="foglamp.storage.postgres"
 
     # Check log severity
     if ! [[ "$1" =~ ^(debug|info|notice|err|crit|alert|emerg)$ ]]; then
-        pg_log "err" "Internal error: unrecognized priority: $1" $3
+        write_log "err" "Internal error: unrecognized priority: $1" $3
         exit 1
     fi
 
@@ -91,43 +109,43 @@ pg_start() {
         "0")
             # PostgreSQL already running.
             if [[ "$1" == "noisy" ]]; then
-                pg_log "info" "PostgreSQL is already running." "all" "pretty"
+                write_log "info" "PostgreSQL is already running." "all" "pretty"
             else
-                pg_log "info" "PostgreSQL is already running." "logonly" "pretty"
+                write_log "info" "PostgreSQL is already running." "logonly" "pretty"
             fi
             ;;
 
         "2")
             if [[ "$MANAGED" = false ]]; then
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "Unable to start PostgreSQL. The server is not managed by FogLAMP." "all" "pretty"
+                    write_log "info" "Unable to start PostgreSQL. The server is not managed by FogLAMP." "all" "pretty"
                 fi
                 exit 2
             fi
 
             # PostgreSQL not running - starting
             if [[ "$1" == "noisy" ]]; then
-                pg_log "info" "Starting PostgreSQL..." "all" "pretty"
+                write_log "info" "Starting PostgreSQL..." "all" "pretty"
             else
-                pg_log "info" "Starting PostgreSQL..." "logonly" "pretty"
+                write_log "info" "Starting PostgreSQL..." "logonly" "pretty"
             fi
             eval $PG_CTL_COMMAND start > /dev/null 2>&1
 
             check_again=`pg_status "silent"`
             if [[ "$check_again" -eq "0" ]]; then
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL started." "all" "pretty"
+                    write_log "info" "PostgreSQL started." "all" "pretty"
                 else
-                    pg_log "info" "PostgreSQL started." "logonly" "pretty"
+                    write_log "info" "PostgreSQL started." "logonly" "pretty"
                 fi
             else
-                pg_log "err" "Unable to start PostgreSQL." "all"
+                write_log "err" "Unable to start PostgreSQL." "all"
                 exit 1
             fi
             ;;
 
         *)
-            pg_log "err" "Unknown database return status." "all"
+            write_log "err" "Unknown database return status." "all"
             exit 1
             ;;
     esac
@@ -151,9 +169,9 @@ pg_stop() {
         # UNMANAGED part
 
         if [[ "$1" == "noisy" ]]; then
-            pg_log "info" "Unable to stop PostgreSQL. The server is not managed by FogLAMP." "all" "pretty"
+            write_log "info" "Unable to stop PostgreSQL. The server is not managed by FogLAMP." "all" "pretty"
         else
-            pg_log "info" "Unable to stop PostgreSQL. The server is not managed by FogLAMP." "logonly" "pretty"
+            write_log "info" "Unable to stop PostgreSQL. The server is not managed by FogLAMP." "logonly" "pretty"
         fi
 
     else
@@ -165,35 +183,35 @@ pg_stop() {
         case "$result" in
             "0")
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "Stopping PostgreSQL..." "all" "pretty"
+                    write_log "info" "Stopping PostgreSQL..." "all" "pretty"
                 else
-                    pg_log "info" "Stopping PostgreSQL..." "logonly" "pretty"
+                    write_log "info" "Stopping PostgreSQL..." "logonly" "pretty"
                 fi
                 eval $PG_CTL_COMMAND stop > /dev/null 2>&1
 
                 check_again=`pg_status "silent"`
                 if [[ "$check_again" -eq "2" ]]; then
                     if [[ "$1" == "noisy" ]]; then
-                        pg_log "info" "PostgreSQL stopped." "all" "pretty"
+                        write_log "info" "PostgreSQL stopped." "all" "pretty"
                     else
-                        pg_log "info" "PostgreSQL stopped." "logonly" "pretty"
+                        write_log "info" "PostgreSQL stopped." "logonly" "pretty"
                     fi
                 else
-                    pg_log "err" "Unable to stop PostgreSQL." "all"
+                    write_log "err" "Unable to stop PostgreSQL." "all"
                     exit 1
                 fi
                 ;;
 
             "2")
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL is not running." "all" "pretty"
+                    write_log "info" "PostgreSQL is not running." "all" "pretty"
                 else
-                    pg_log "info" "PostgreSQL is not running." "logonly" "pretty"
+                    write_log "info" "PostgreSQL is not running." "logonly" "pretty"
                 fi
                 ;;
 
             *)
-                pg_log "err" "Unknown database return status." "all"
+                write_log "err" "Unknown database return status." "all"
                 exit 1
                 ;;
         esac
@@ -223,16 +241,16 @@ pg_reset() {
     fi
 
     if [[ "$1" == "noisy" ]]; then
-        pg_log "info" "Building the metadata for the FogLAMP Plugin..." "all" "pretty"
+        write_log "info" "Building the metadata for the FogLAMP Plugin..." "all" "pretty"
     else
-        pg_log "info" "Building the metadata for the FogLAMP Plugin..." "logonly" "pretty"
+        write_log "info" "Building the metadata for the FogLAMP Plugin..." "logonly" "pretty"
     fi
        
     eval $PG_SQL -d postgres -q -f $INIT_SQL > /dev/null 2>&1
     if [[ "$1" == "noisy" ]]; then
-        pg_log "info" "Build complete." "all" "pretty"
+        write_log "info" "Build complete." "all" "pretty"
     else
-        pg_log "info" "Build complete." "logonly" "pretty"
+        write_log "info" "Build complete." "logonly" "pretty"
     fi
 
 }
@@ -267,9 +285,9 @@ pg_status() {
         if ! [[ -d "$PG_DATA/base" ]]; then
 
             if [[ "$1" == "noisy" ]]; then
-                pg_log "info" "Initializing PostgreSQL." "all" "pretty"
+                write_log "info" "Initializing PostgreSQL." "all" "pretty"
             else
-                pg_log "info" "Initializing PostgreSQL." "logonly" "pretty"
+                write_log "info" "Initializing PostgreSQL." "logonly" "pretty"
             fi
             eval $PG_CTL_COMMAND init > /dev/null 2>&1
 
@@ -280,20 +298,20 @@ pg_status() {
         case "$($cmd_to_exec)" in
             "pg_ctl: no server running")
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL not running." "outonly" "pretty"
+                    write_log "info" "PostgreSQL not running." "outonly" "pretty"
                 else
                     echo "2"
                 fi    
                 ;;
             "pg_ctl: server is running"*)
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL running." "outonly" "pretty"
+                    write_log "info" "PostgreSQL running." "outonly" "pretty"
                 else
                     echo "0"
                 fi
                 ;;
             *)
-                pg_log "err" "Unrecognized PostgreSQL status." "all"
+                write_log "err" "Unrecognized PostgreSQL status." "all"
                 exit 1
                 ;;
         esac
@@ -302,8 +320,8 @@ pg_status() {
 
         # The unmanaged part
         if ! [[ -x "$(command -v pg_isready)" ]]; then
-            pg_log "info" "Status check cannot be found. Is PostgreSQL installed?" "outonly" "pretty"
-            pg_log "info" "If PostgreSQL is installed, check if the bin dir is in the PATH." "outonly" "pretty"
+            write_log "info" "Status check cannot be found. Is PostgreSQL installed?" "outonly" "pretty"
+            write_log "info" "If PostgreSQL is installed, check if the bin dir is in the PATH." "outonly" "pretty"
             exit 1
         fi
 
@@ -311,20 +329,20 @@ pg_status() {
         case "${ret_message}" in
             *"no response")
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL not running." "outonly" "pretty"
+                    write_log "info" "PostgreSQL not running." "outonly" "pretty"
                 else
                     echo "2"
                 fi
                 ;;
             *"accepting connections")
                 if [[ "$1" == "noisy" ]]; then
-                    pg_log "info" "PostgreSQL running." "outonly" "pretty"
+                    write_log "info" "PostgreSQL running." "outonly" "pretty"
                 else
                     echo "0"
                 fi
                 ;;
             *)
-                pg_log "err" "Unknow status return by the PostgreSQL database server." "all"
+                write_log "err" "Unknow status return by the PostgreSQL database server." "all"
                 exit 1
         esac
 
@@ -369,24 +387,6 @@ case "$2" in
             export PGHOST
         fi
 
-        # Set FOGLAMP_DATA if it does not exist
-        if [ -z ${FOGLAMP_DATA+x} ]; then
-            FOGLAMP_DATA="${HOME}/foglamp"
-        fi
-
-        # Check if $FOGLAMP_DATA exists
-        if [[ -e ${FOGLAMP_DATA} ]]; then
-
-            # Check if $FOGLAMP_DATA is a directory
-            if [[ ! -d ${FOGLAMP_DATA} ]]; then
-                pg_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
-                exit 1
-            fi
-        else
-            # $FOGLAMP_DATA does not exist: create it
-            mkdir -p ${FOGLAMP_DATA}
-        fi
-
         PG_DIR="${FOGLAMP_DATA}/storage/postgres/pgsql"
         PG_DATA="${PG_DIR}/data"
         PG_LOG="${PG_DIR}/logger"
@@ -395,14 +395,14 @@ case "$2" in
         PG_CTL="$FOGLAMP_ROOT/plugins/storage/postgres/pgsql/bin/pg_ctl"
         PG_CTL_COMMAND="$PG_CTL -w -D $PG_DATA -l $PG_LOG"
         if ! [[ -x "${PG_CTL}" ]]; then
-            pg_log "err" "PostgreSQL program pg_ctl not found: the database server cannot be managed." "all" "pretty"
+            write_log "err" "PostgreSQL program pg_ctl not found: the database server cannot be managed." "all" "pretty"
             exit 1
         fi
 
         # Check if psql is present in the expected path
         PG_SQL="$FOGLAMP_ROOT/plugins/storage/postgres/pgsql/bin/psql"
         if ! [[ -x "${PG_SQL}" ]]; then
-            pg_log "err" "PostgreSQL program psql not found: the database server cannot be managed." "all" "pretty"
+            write_log "err" "PostgreSQL program psql not found: the database server cannot be managed." "all" "pretty"
             exit 1
         fi
 
@@ -414,8 +414,8 @@ case "$2" in
         # This case includes UNMANAGED
 
         if ! [[ -x "$(command -v psql)" ]]; then
-            pg_log "info" "The psql command cannot be found. Is PostgreSQL installed?" "outonly" "pretty"
-            pg_log "info" "If PostgreSQL is installed, check if the bin dir is in the PATH." "outonly" "pretty"
+            write_log "info" "The psql command cannot be found. Is PostgreSQL installed?" "outonly" "pretty"
+            write_log "info" "If PostgreSQL is installed, check if the bin dir is in the PATH." "outonly" "pretty"
             exit 1
         else
             PG_SQL="$(command -v psql)"
@@ -438,7 +438,7 @@ else
     if [[ -e "$FOGLAMP_ROOT/C/plugins/storage/postgres/init.sql" ]]; then
         INIT_SQL="$FOGLAMP_ROOT/C/plugins/storage/postgres/init.sql"
     else
-        pg_log "err" "Missing initialization file init.sql." "all" "pretty"
+        write_log "err" "Missing initialization file init.sql." "all" "pretty"
         exit 1
     fi
 fi
