Fixed issue with write_log

diff --git a/scripts/foglamp b/scripts/foglamp
--- a/scripts/foglamp
+++ b/scripts/foglamp
@@ -24,7 +24,6 @@ set -e
 #
 USAGE="Usage: `basename ${0}` {start|stop|status|help}"
 
-
 # Check FOGLAMP_ROOT
 if [ -z ${FOGLAMP_ROOT+x} ]; then
     # Set FOGLAMP_ROOT as the default directory
@@ -34,78 +33,24 @@ fi
 
 # Check if the default directory exists
 if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory." "all" "pretty"
-    write_log "info" "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP." "outonly" "pretty"
-    write_log "info" "Specify the base directory for FogLAMP and set the variable with:" "outonly" "pretty"
-    write_log "info" "export FOGLAMP_ROOT=<basedir>" "outonly" "pretty"
+    logger -p local0.err -t "foglamp.script.foglamp" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
+    echo "Specify the base directory for FogLAMP and set the variable with:"
+    echo "export FOGLAMP_ROOT=<basedir>"
     exit 1
 fi
 
-# Set FOGLAMP_DATA if it does not exist
-if [ -z ${FOGLAMP_DATA+x} ]; then
-    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
-    export FOGLAMP_DATA
-fi
 
-# Check if $FOGLAMP_DATA exists and is a directory
-if [[ ! -d ${FOGLAMP_DATA} ]]; then
-    write_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
-    exit 1
-fi
-
-# Check if the configuration file exists
-if [[ ! -e "$FOGLAMP_DATA/etc/foglamp.json" ]]; then
-
-    # Missing configuration file
-    write_log "err" "FogLAMP cannot start." "all" "pretty"
-    write_log "err" "FogLAMP configuration file foglamp.json not found." "all" "pretty"
-    exit 1
-
-fi
+##########
+## INCLUDE SECTION
+##########
+. $FOGLAMP_ROOT/scripts/common/write_log.sh
 
 
-## The Logging Handler
-#
-# Paramaters: $1 - Severity:
-#                  - debug
-#                  - info
-#                  - notice
-#                  - err
-#                  - crit
-#                  - alert
-#                  - emerg
-#             $2 - Message
-#             $3 - Output:
-#                  - logonly : send the message only to syslog
-#                  - all     : send the message to syslog and stdout
-#                  - outonly " send the message only to stdout
-#             $4 - Format
-#                - pretty : Do not show the date and priority
-#
-write_log() {
-
-    MODULE="foglamp.core"
-
-    # Check log severity
-    if ! [[ "$1" =~ ^(debug|info|notice|err|crit|alert|emerg)$ ]]; then
-        write_log "err" "Internal error: unrecognized priority: $1" $3
-        exit 1
-    fi
-
-    # Log to syslog
-    if [[ "$3" =~ ^(logonly|all)$ ]]; then
-        logger -p local0.$1 -t $MODULE $2
-    fi
-
-    # Log to Stdout
-    if [[ "$3" =~ ^(outonly|all)$ ]]; then
-        if [[ "$4" == "pretty" ]]; then
-            echo "$2" >&2
-        else
-            echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $@" >&2
-        fi
-    fi
-
+## Logger wrapper
+foglamp_log() {
+    write_log "foglamp.script.foglamp" "$1" "$2" "$3" "$4"
 }
 
 
@@ -114,14 +59,14 @@ foglamp_start() {
 
     # Check the storage management script
     if [[ ! -e "$FOGLAMP_ROOT/scripts/storage" ]]; then
-        write_log "info" "FogLAMP cannot start." "all" "pretty"
-        write_log "err" "FogLAMP Storage Plugin script not found." "all" "pretty"
+        foglamp_log "info" "FogLAMP cannot start." "all" "pretty"
+        foglamp_log "err" "FogLAMP Storage Plugin script not found." "all" "pretty"
         exit 1
     fi
 
     # Check the Python environment
     if ! [[ -x "$(command -v python3)" ]]; then
-        write_log "err" "Python interpreter not found, FogLAMP cannot start." "all" "pretty"
+        foglamp_log "err" "Python interpreter not found, FogLAMP cannot start." "all" "pretty"
         exit 1
     fi
 
@@ -135,7 +80,7 @@ foglamp_start() {
 
         "0")
             #FogLAMP already running
-            write_log "info" "FogLAMP is already running." "all" "pretty"
+            foglamp_log "info" "FogLAMP is already running." "all" "pretty"
             ;;
 
         "2")
@@ -144,15 +89,15 @@ foglamp_start() {
             export PYTHONPATH
             if [[ -e "$PYTHONPATH/foglamp/services/core/__main__.py" ]]; then
                 python3 -m foglamp.services.core > /dev/null 2>&1 & disown
-                write_log "info" "FogLAMP started." "all" "pretty"
+                foglamp_log "info" "FogLAMP started." "all" "pretty"
             else
-                write_log "err" "FogLAMP core not found." "all" "pretty"
+                foglamp_log "err" "FogLAMP core not found." "all" "pretty"
                 exit 1
             fi
             ;;
 
         *)
-            write_log "err" "Unknown return status." "all"
+            foglamp_log "err" "Unknown return status." "all"
             exit 1
             ;;
     esac
@@ -168,8 +113,8 @@ foglamp_stop() {
 
     # Check the storage management script
     if [[ ! -e "$FOGLAMP_ROOT/scripts/storage" ]]; then
-        write_log "info" "FogLAMP cannot be stopped." "all" "pretty"
-        write_log "err" "FogLAMP Storage Plugin script not found." "all" "pretty"
+        foglamp_log "info" "FogLAMP cannot be stopped." "all" "pretty"
+        foglamp_log "err" "FogLAMP Storage Plugin script not found." "all" "pretty"
         exit 1
     fi
 
@@ -187,7 +132,7 @@ foglamp_stop() {
     #       it deals with the database engine.
     source "$FOGLAMP_ROOT/scripts/storage" stop
     
-    write_log "info" "FogLAMP stopped." "all" "pretty"
+    foglamp_log "info" "FogLAMP stopped." "all" "pretty"
 
 }
 
@@ -198,8 +143,8 @@ foglamp_status() {
 
     # Check if curl is present
     if [[ ! `command -v curl` ]]; then
-        write_log "info" "FogLAMP cannot be checked." "outonly" "pretty"
-        write_log "info" "The curl command cannot be executed." "outonly" "pretty"
+        foglamp_log "info" "FogLAMP cannot be checked." "outonly" "pretty"
+        foglamp_log "info" "The curl command cannot be executed." "outonly" "pretty"
     fi
 
     result=`curl -s http://localhost:8081/foglamp/ping || true`
@@ -210,12 +155,12 @@ foglamp_status() {
                 echo "0"
             else
                 tot_sec=`echo $result | cut -d":" -f2 | cut -d"." -f1`
-                write_log "info" "FogLAMP running." "outonly" "pretty"
-                write_log "info" "FogLAMP uptime: $tot_sec seconds." "outonly" "pretty"
+                foglamp_log "info" "FogLAMP running." "outonly" "pretty"
+                foglamp_log "info" "FogLAMP uptime: $tot_sec seconds." "outonly" "pretty"
 
                 # Show Services
-                write_log "info" "=== FogLAMP services:" "outonly" "pretty"
-                write_log "info" "foglamp.services.core" "outonly" "pretty"
+                foglamp_log "info" "=== FogLAMP services:" "outonly" "pretty"
+                foglamp_log "info" "foglamp.services.core" "outonly" "pretty"
                 ps -ef | grep "$FOGLAMP_ROOT//services/storage" | grep -v 'grep' | awk '{print "foglamp.services.storage " $9 " " $10}' || true
                 ps -ef | grep "$FOGLAMP_ROOT//services/south" | grep -v 'grep' | awk '{print "foglamp.services.south " $9 " " $10}' || true
                 ps -ef | grep "$FOGLAMP_ROOT//services/north" | grep -v 'grep' | awk '{print "foglamp.services.north " $9 " " $10}' || true
@@ -223,7 +168,7 @@ foglamp_status() {
                 ps -ef | grep -o 'python3 -m foglamp.services.north.*' | grep -o 'foglamp.services.north.*' | grep -v 'foglamp.services.north\.\*' || true
 
                 # Show Tasks
-                write_log "info" "=== FogLAMP tasks:" "outonly" "pretty"
+                foglamp_log "info" "=== FogLAMP tasks:" "outonly" "pretty"
                 ps -ef | grep -o 'python3 -m foglamp.tasks.*' | grep -o 'foglamp.tasks.*' | grep -v 'foglamp.tasks\.\*' || true
             fi
             ;;
@@ -232,13 +177,13 @@ foglamp_status() {
                 if [[ "$1" == "silent" ]]; then
                     echo "0"
                 else
-                    write_log "info" "FogLAMP starting." "outonly" "pretty"
+                    foglamp_log "info" "FogLAMP starting." "outonly" "pretty"
                 fi
             else
                 if [[ "$1" == "silent" ]]; then
                     echo "2"
                 else
-                    write_log "info" "FogLAMP not running." "outonly" "pretty"
+                    foglamp_log "info" "FogLAMP not running." "outonly" "pretty"
                 fi
             fi
             ;;
@@ -262,6 +207,29 @@ Arguments:
 
 
 ### Main Logic ###
+
+# Set FOGLAMP_DATA if it does not exist
+if [ -z ${FOGLAMP_DATA+x} ]; then
+    FOGLAMP_DATA="${FOGLAMP_ROOT}/data"
+    export FOGLAMP_DATA
+fi
+
+# Check if $FOGLAMP_DATA exists and is a directory
+if [[ ! -d ${FOGLAMP_DATA} ]]; then
+    foglamp_log "err" "FogLAMP cannot be executed: ${FOGLAMP_DATA} is not a valid directory." "all" "pretty"
+    exit 1
+fi
+
+# Check if the configuration file exists
+if [[ ! -e "$FOGLAMP_DATA/etc/foglamp.json" ]]; then
+
+    # Missing configuration file
+    foglamp_log "err" "FogLAMP cannot start." "all" "pretty"
+    foglamp_log "err" "FogLAMP configuration file foglamp.json not found." "all" "pretty"
+    exit 1
+
+fi
+
 case "$1" in
     start)
         foglamp_start
