FOGL-1322: Working stage.

diff --git a/scripts/tasks/backup_postgres b/scripts/tasks/backup_postgres
--- a/scripts/tasks/backup_postgres
+++ b/scripts/tasks/backup_postgres
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+declare FOGLAMP_ROOT
+declare FOGLAMP_DATA
+declare PYTHONPATH
+
 # Run a FogLAMP task written in Python
 if [ "${FOGLAMP_ROOT}" = "" ]; then
 	FOGLAMP_ROOT=/usr/local/foglamp
@@ -21,18 +25,24 @@ if [ "${PYTHONPATH}" = "" ]; then
 	export PYTHONPATH="${FOGLAMP_ROOT}/python"
 fi
 
+export FOGLAMP_DATA=$FOGLAMP_ROOT/data
 
 # Include common code
 source "${FOGLAMP_ROOT}/scripts/common/get_storage_plugin.sh"
 
-# Evaluates with storage is enabled and it uses the problems commands
+# Evaluates which storage engine is enabled and it uses the proper command
 storage=`get_storage_plugin`
 
 if [ "${storage}" == "sqlite" ]; then
 
     python3 -m foglamp.plugins.storage.sqlite.backup_restore.backup_sqlite $@
-else
+
+elif [ "${storage}" == "postgres" ]; then
+
     python3 -m foglamp.plugins.storage.postgres.backup_restore.backup_postgres $@
+else
+    logger "ERROR: the backup functionality for the storage engine :${storage}: is not implemented."
+    exit 1
 fi
 
 
diff --git a/scripts/tasks/restore_postgres b/scripts/tasks/restore_postgres
--- a/scripts/tasks/restore_postgres
+++ b/scripts/tasks/restore_postgres
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+declare FOGLAMP_ROOT
+declare FOGLAMP_DATA
+declare PYTHONPATH
+
 # Run a FogLAMP task written in Python
 if [ "${FOGLAMP_ROOT}" = "" ]; then
 	FOGLAMP_ROOT=/usr/local/foglamp
@@ -21,19 +25,27 @@ if [ "${PYTHONPATH}" = "" ]; then
 	export PYTHONPATH="${FOGLAMP_ROOT}/python"
 fi
 
+export FOGLAMP_DATA=$FOGLAMP_ROOT/data
+
 # Include common code
 source "${FOGLAMP_ROOT}/scripts/common/get_storage_plugin.sh"
 
-# Evaluates with storage is enabled and it uses the problems commands
+# Evaluates which storage engine is enabled and it uses the proper command
 storage=`get_storage_plugin`
 
 if [ "${storage}" == "sqlite" ]; then
 
     command="python3 -m foglamp.plugins.storage.sqlite.backup_restore.restore_sqlite $@"
-else
+    # Avoid FogLAMP termination at the FogLAMP stop
+    nohup $command </dev/null >/dev/null 2>&1 &
+
+elif [ "${storage}" == "postgres" ]; then
+
     command="python3 -m foglamp.plugins.storage.postgres.backup_restore.restore_postgres $@"
+    # Avoid FogLAMP termination at the FogLAMP stop
+    nohup $command </dev/null >/dev/null 2>&1 &
+
+else
+    logger "ERROR: the restore functionality for the storage engine :${storage}: is not implemented."
+    exit 1
 fi
-
-# Avoid FogLAMP termination at the FogLAMP stop
-nohup $command </dev/null >/dev/null 2>&1 &
-
